# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

executor: node
steps:
  - checkout
  - restore_yarn_cache
  - run:
      name: Install UI dependencies
      command: |
        cd ui
        yarn install
        npm rebuild node-sass
  - save_yarn_cache
