---
name: enos_fmt

on:
  pull_request:
    paths:
      - enos/**

jobs:
  fmt_check:
    # Only run this workflow on pull requests from hashicorp/vault branches
    # as we need secrets to install enos.
    if: "! github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          # Terraform 1.4.x introduced an issue that prevents some resources from
          # planning. Pin to 1.3.x until it is resolved.
          terraform_version: 1.3.9
      - uses: hashicorp/action-setup-enos@v1
        with:
          github-token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: check formatting
        working-directory: ./enos
        run: make check-fmt
